### List Users
# @name listUsers
GET {{baseUrl}}/users
x-api-key: {{apiKey}}

### Create User
# @name createUser
POST {{baseUrl}}/users
x-api-key: {{apiKey}}
Content-Type: application/json

{
    "name": "Antonio Reuter",
    "email": "antonioreuter@gmail.com"
}

@createdId = {{createUser.UserId}}

### Get User
# @name getUser
GET {{baseUrl}}/users/{{createdId}}
x-api-key: {{apiKey}}

### Delete User
# @name deleteUser
DELETE {{baseUrl}}/users/{{createdId}}
x-api-key: {{apiKey}}

