AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Validator User API - Agent Ready

Parameters:
  RepositoryName:
    Type: String
    Description: The repository name for tagging
  CommitHash:
    Type: String
    Description: The Git commit hash for tagging

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: !Ref UsersTable
    Tags:
      Service: UserManagementAPI
      RepositoryName: !Ref RepositoryName
      HashCommit: !Ref CommitHash

Resources:
  # --- 1. Database ---
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PocValidator-Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: Email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # --- 2. API Gateway ---
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: ApiKeyAuthorizer
        Authorizers:
          ApiKeyAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Headers:
                - x-api-key
            AuthorizerResultTtlInSeconds: 0

  # --- 3. Lambda Functions ---

  # Custom Authorizer
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/authorizer.handler
    Metadata: &EsbuildConfig
      BuildMethod: esbuild
      BuildProperties: &EsbuildProperties
        Minify: true
        Target: "node22"
        EntryPoints:
          - src/handlers/authorizer.ts

  # Create User (POST)
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/create-user.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !GetAtt UsersTable.Arn
                - !Sub "${UsersTable.Arn}/index/*"
      Events:
        PostUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /users
            Method: post
    Metadata:
      <<: *EsbuildConfig
      BuildProperties:
        <<: *EsbuildProperties
        EntryPoints:
          - src/handlers/create-user.ts

  # Get User (GET)
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/get-user.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt UsersTable.Arn
      Events:
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /users/{id}
            Method: get
    Metadata:
      <<: *EsbuildConfig
      BuildProperties:
        <<: *EsbuildProperties
        EntryPoints:
          - src/handlers/get-user.ts

  # List Users (GET)
  ListUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/list-users.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !GetAtt UsersTable.Arn
      Events:
        ListUsers:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /users
            Method: get
    Metadata:
      <<: *EsbuildConfig
      BuildProperties:
        <<: *EsbuildProperties
        EntryPoints:
          - src/handlers/list-users.ts

  # Delete User (DELETE)
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/delete-user.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt UsersTable.Arn
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /users/{id}
            Method: delete
    Metadata:
      <<: *EsbuildConfig
      BuildProperties:
        <<: *EsbuildProperties
        EntryPoints:
          - src/handlers/delete-user.ts

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
